Repository SCM-NV/qmflows, pull requests merged in 2020-03, with the labels that each got.

#146 Package & Result additions
  .gitignore
  src/qmflows/packages/SCM.py
  src/qmflows/packages/cp2k_package.py
  src/qmflows/packages/gamess.py
  src/qmflows/packages/orca.py
  src/qmflows/packages/packages.py
Labels: enhancement

#149 Introduction of PackageWrapper & ResultWrapper
  docs/conf.py
  docs/documentation.rst
  docs/package_wrapper.rst
  setup.py
  src/qmflows/__init__.py
  src/qmflows/data/dictionaries/generic2None.json
  src/qmflows/data/dictionaries/propertiesNone.json
  src/qmflows/packages/SCM.py
  src/qmflows/packages/__init__.py
  src/qmflows/packages/cp2k_package.py
  src/qmflows/packages/gamess.py
  src/qmflows/packages/orca.py
  src/qmflows/packages/package_wrapper.py
  src/qmflows/packages/packages.py
  src/qmflows/utils.py
  test/test_files/ADFjob.dill
  test/test_files/AMSJob.dill
  test/test_using_plams/test_package_wrapper.py
Labels: bug, enhancement

#151 Documentation and Init_restart() update
  requirements.txt
  src/qmflows/utils.py
Labels: Documentation, bug, enhancement

#155 API documentation update
  docs/_packages.rst
  docs/conf.py
  src/qmflows/packages/SCM.py
  src/qmflows/packages/cp2k_mm.py
  src/qmflows/packages/cp2k_package.py
  src/qmflows/packages/gamess.py
  src/qmflows/packages/orca.py
  src/qmflows/packages/package_wrapper.py
  src/qmflows/packages/packages.py
Labels: Documentation

#161 pandas somehow disappeared from install_requires
  setup.py
Labels: Documentation

#164 Package and CP2KMM upgrades
  src/qmflows/common.py
  src/qmflows/cp2k_utils.py
  src/qmflows/packages/SCM.py
  src/qmflows/packages/cp2k_mm.py
  src/qmflows/packages/cp2k_package.py
  src/qmflows/packages/gamess.py
  src/qmflows/packages/orca.py
  src/qmflows/packages/package_wrapper.py
  src/qmflows/packages/packages.py
  src/qmflows/parsers/cp2KParser.py
  src/qmflows/templates/templates.py
  src/qmflows/type_hints.py
  src/qmflows/warnings_qmflows.py
  test/test_using_plams/test_cp2k_mm.py
Labels: enhancement

#163 Add more tests
  .github/workflows/pythonapp.yml
  .travis.yml
  src/qmflows/data/dictionaries/propertiesADF.yaml
  src/qmflows/data/dictionaries/propertiesORCA.yaml
  src/qmflows/packages/cp2k_package.py
  src/qmflows/packages/packages.py
  src/qmflows/parsers/adf_parser.py
  src/qmflows/parsers/generic_parsers.py
  src/qmflows/parsers/orca_parser.py
  test/test_adf_mock.py
  test/test_adf_parser.py
  test/test_cp2k_mock.py
  test/test_cp2k_parser.py
  test/test_files/orca_freq_ethylene.hess
  test/test_files/orca_output/ORCAjob.opt
  test/test_files/orca_output/opt_methanol_orca.in
  test/test_files/output_adf/ADFjob/ADFjob.dill
  test/test_files/output_adf/ADFjob/ADFjob.err
  test/test_files/output_adf/ADFjob/ADFjob.in
  test/test_files/output_adf/ADFjob/ADFjob.out
  test/test_files/output_adf/ADFjob/ADFjob.run
  test/test_files/output_adf/ADFjob/ADFjob.t21
  test/test_files/output_adf/ADFjob/logfile
  test/test_files/output_adf/ADFjob/t21.C
  test/test_files/output_adf/ADFjob/t21.H
  test/test_files/output_adf/ADFjob/t21.N
  test/test_files/output_adf/logfile
  test/test_files/output_cp2k/cp2k_job.in
  test/test_files/output_cp2k/cp2k_job/cp2k_job.dill
  test/test_files/output_cp2k/cp2k_job/cp2k_job.in
  test/test_files/output_cp2k/cp2k_job/cp2k_job.out
  test/test_files/output_cp2k/cp2k_job/orbitals.out-1_0.MOLog
  test/test_files/output_cp2k/mo_coeffs.log
  test/test_files/output_orca/ORCAjob/ORCAjob.dill
  test/test_files/output_orca/ORCAjob/ORCAjob.engrad
  test/test_files/output_orca/ORCAjob/ORCAjob.gbw
  test/test_files/output_orca/ORCAjob/ORCAjob.hess
  test/test_files/output_orca/ORCAjob/ORCAjob.in
  test/test_files/output_orca/ORCAjob/ORCAjob.opt
  test/test_files/output_orca/ORCAjob/ORCAjob.out
  test/test_files/output_orca/ORCAjob/ORCAjob.prop
  test/test_files/output_orca/ORCAjob/ORCAjob.run
  test/test_files/output_orca/ORCAjob/ORCAjob.trj
  test/test_files/output_orca/ORCAjob/ORCAjob.xyz
  test/test_files/output_orca/ORCAjob/ORCAjob_property.txt
  test/test_mock_operations.py
  test/test_orca_mock.py
  test/test_overlay.py
  test/test_packages.py
  test/test_parser_orca.py
  test/test_special_keywords.py
  test/test_using_plams/test_opt_orca.py
  test/test_xyz_parser.py
Labels: enhancement

#170 Remove FDE fragmentation
  setup.py
  src/qmflows/__init__.py
  src/qmflows/components/__init__.py
  src/qmflows/components/fde.py
  src/qmflows/components/operations.py
  src/qmflows/examples/Conditional_workflows/calc_freqs.py
  src/qmflows/examples/FDE_Fragments/ADF3FDE_Cystine.py
  src/qmflows/examples/FDE_Fragments/ADF3FDE_Dialanine.py
  src/qmflows/examples/FDE_Fragments/FDE_Fragments.py
  src/qmflows/examples/FDE_Fragments/__init__.py
  src/qmflows/examples/__init__.py
  test/test_using_plams/test_FDE_Fragments.py
Labels: enhancement

#172 increase test coverage
  src/qmflows/fileFunctions.py
  src/qmflows/packages/cp2k_package.py
  test/test_cp2k_mock.py
  test/test_files/output_cp2k/cp2k_freq/cp2k-VIBRATIONS-1.eig
  test/test_files/output_cp2k/cp2k_freq/cp2k-VIBRATIONS-1.mol
  test/test_files/output_cp2k/cp2k_freq/cp2k_freq.dill
  test/test_files/output_cp2k/cp2k_freq/cp2k_freq.err
  test/test_files/output_cp2k/cp2k_freq/cp2k_freq.in
  test/test_files/output_cp2k/cp2k_freq/cp2k_freq.out
  test/test_files/output_cp2k/cp2k_freq/cp2k_freq.run
  test/test_files/output_cp2k/cp2k_opt/cp2k-pos-1.xyz
  test/test_files/output_cp2k/cp2k_opt/cp2k_opt.dill
  test/test_files/output_cp2k/cp2k_opt/cp2k_opt.err
  test/test_files/output_cp2k/cp2k_opt/cp2k_opt.in
  test/test_files/output_cp2k/cp2k_opt/cp2k_opt.out
  test/test_special_keywords.py
  test/test_templates.py
  test/test_yaml_settings.py
Labels: enhancement

#175 Fix DFTB interface using AMS
  src/qmflows/data/dictionaries/generic2DFTB.yaml
  src/qmflows/data/dictionaries/propertiesDFTB.yaml
  src/qmflows/packages/SCM.py
  src/qmflows/packages/packages.py
  src/qmflows/parsers/adf_parser.py
  src/qmflows/templates/templates.py
  test/test_cp2k_mock.py
  test/test_dftb_mock.py
  test/test_files/output_dftb/dftb_freq/ams.rkf
  test/test_files/output_dftb/dftb_freq/dftb.rkf
  test/test_files/output_dftb/dftb_freq/dftb_freq.dill
  test/test_files/output_dftb/dftb_freq/dftb_freq.err
  test/test_files/output_dftb/dftb_freq/dftb_freq.in
  test/test_files/output_dftb/dftb_freq/dftb_freq.out
  test/test_files/output_dftb/dftb_freq/dftb_freq.run
  test/test_files/output_dftb/dftb_geometry/ams.rkf
  test/test_files/output_dftb/dftb_geometry/dftb.rkf
  test/test_files/output_dftb/dftb_geometry/dftb_geometry.dill
  test/test_files/output_dftb/dftb_geometry/dftb_geometry.err
  test/test_files/output_dftb/dftb_geometry/dftb_geometry.in
  test/test_files/output_dftb/dftb_geometry/dftb_geometry.out
Labels: enhancement

#181 Added tests for CP2KMM specific keywords; removed some dead code
  src/qmflows/packages/cp2k_mm.py
  src/qmflows/test_utils.py
  test/test_files/cp2k_mm_special_keyword.yaml
  test/test_special_keywords.py
Labels: enhancement

#178 Increase test coverage
  src/qmflows/common.py
  src/qmflows/examples/Constrained_and_TS_optimizations/generic_constraints.py
  src/qmflows/packages/SCM.py
  src/qmflows/packages/cp2k_package.py
  src/qmflows/packages/orca.py
  src/qmflows/packages/packages.py
  src/qmflows/parsers/cp2KParser.py
  src/qmflows/parsers/generic_parsers.py
  src/qmflows/parsers/orca_parser.py
  src/qmflows/parsers/parser.py
  src/qmflows/utils.py
  test/test_adf_mock.py
  test/test_cp2k_mock.py
  test/test_cp2k_parser.py
  test/test_orca_mock.py
  test/test_orca_parser.py
  test/test_parser_orca.py
  test/test_special_keywords.py
Labels: enhancement

#184 Added static code tests using MyPy
  setup.py
  src/qmflows/backports.py
  src/qmflows/common.py
  src/qmflows/components/operations.py
  src/qmflows/cp2k_utils.py
  src/qmflows/parsers/adf_parser.py
  src/qmflows/parsers/cp2KParser.py
  src/qmflows/parsers/generic_parsers.py
  src/qmflows/parsers/orca_parser.py
  src/qmflows/parsers/parser.py
  src/qmflows/parsers/xyzParser.py
  src/qmflows/test_utils.py
  src/qmflows/utils.py
  src/qmflows/warnings_qmflows.py
  test/test_files/mypy.ini
  test/test_mypy.py
  test/test_warnings.py
Labels: enhancement

#186 Package and Result update
  docs/_packages.rst
  setup.cfg
  setup.py
  src/qmflows/data/dictionaries/generic2PackageWrapper.yaml
  src/qmflows/data/dictionaries/generic2gamess.yaml
  src/qmflows/data/dictionaries/propertiesPackageWrapper.yaml
  src/qmflows/fileFunctions.py
  src/qmflows/packages/SCM.py
  src/qmflows/packages/__init__.py
  src/qmflows/packages/cp2k_mm.py
  src/qmflows/packages/cp2k_package.py
  src/qmflows/packages/orca.py
  src/qmflows/packages/package_wrapper.py
  src/qmflows/packages/packages.py
  src/qmflows/settings.py
  src/qmflows/type_hints.py
  test/test_cp2k_mock.py
  test/test_mypy.py
Labels: enhancement

#187 Call cp2k in the CI workflows
  .github/workflows/pythonapp.yml
  .travis.yml
  src/qmflows/test_utils.py
  test/test_cp2k_mock.py
  test/test_using_plams/test_cp2k_opt.py
Labels: enhancement

#188 Added the prm_to_df() function
  docs/conf.py
  requirements.txt
  setup.py
  src/qmflows/cp2k_utils.py
  src/qmflows/py.typed
  test/test_cp2k_utils.py
Labels: Documentation, enhancement
