Repository SCM-NV/qmflows, pull requests merged in 2020-06, with the labels that each got.

#198 Use `InitRestart` when running QMFlows jobs
  CHANGELOG.md
  src/qmflows/__init__.py
  src/qmflows/__version__.py
  src/qmflows/packages/packages.py
Labels: enhancement

#199 allow other cp2k executables
  CHANGELOG.md
  src/qmflows/__version__.py
  src/qmflows/packages/cp2k_package.py
Labels: enhancement

#200 Added tests for generating sphinx documentation
  .github/workflows/pythonapp.yml
  .readthedocs.yml
  .travis.yml
  CHANGELOG.md
  docs/_packages.rst
  docs/conf.py
  requirements.txt
  setup.py
  src/qmflows/__version__.py
  test/test_sphinx.py
Labels: Documentation, Tests

#201 Cleaned up the `build with conda` recipe a bit
  .github/workflows/pythonapp.yml
Labels: Tests

#203 Run pydocstyle and pycodestyle over src/
  .github/workflows/pythonapp.yml
  .travis.yml
  codecov.yml
  setup.cfg
  src/qmflows/components/reactivity.py
  src/qmflows/cp2k_utils.py
  src/qmflows/data/__init__.py
  src/qmflows/data/dictionaries/__init__.py
  src/qmflows/examples/Conditional_workflows/__init__.py
  src/qmflows/examples/Conditional_workflows/calc_freqs.py
  src/qmflows/examples/Constrained_and_TS_optimizations/H2O2_TS.py
  src/qmflows/examples/Constrained_and_TS_optimizations/__init__.py
  src/qmflows/examples/Constrained_and_TS_optimizations/generic_constraints.py
  src/qmflows/examples/Constrained_and_TS_optimizations/partial_geometry_opt.py
  src/qmflows/examples/__init__.py
  src/qmflows/packages/SCM.py
  src/qmflows/packages/__init__.py
  src/qmflows/packages/cp2k_mm.py
  src/qmflows/packages/cp2k_package.py
  src/qmflows/packages/orca.py
  src/qmflows/packages/serializer.py
  src/qmflows/parsers/cp2KParser.py
  src/qmflows/settings.py
  src/qmflows/templates/__init__.py
Labels: Tests

#206 Deactivate Travis and run MacOs on GH actions
  .github/workflows/pythonapp.yml
  .travis.yml
  setup.py
Labels: Tests

#207 Added doctests
  conftest.py
  docs/conf.py
  setup.cfg
  src/qmflows/backports.py
  src/qmflows/cp2k_utils.py
  src/qmflows/packages/package_wrapper.py
  src/qmflows/packages/packages.py
  src/qmflows/settings.py
  src/qmflows/test_utils.py
  src/qmflows/utils.py
Labels: Tests
